options:
  formatter: stylish

rules:
  property-sort-order: 2
  class-name-format:
    - 2
    -
      convention: 'mt_([a-z0-9\-]+)'
      convention-explanation: 'All class names must be prefaced with "mt_" and contain only lowercase letters and dashes afterward'
  variable-name-format:
    - 2
    -
      convention: 'mt_([a-z0-9\-]+)'
      convention-explanation: 'All variable names must be prefaced with "mt_" and contain only lowercase letters and dashes afterward'
