#########################
## Sample Sass Lint File
#########################
# File Options
options:
  formatter: stylish

rules:
  property-sort-order: 2
  class-name-format:
    - 2
    -
      convention: 'mt_([a-z0-9\-]+)'
      convention-explanation: 'All class names must be prefaced with "mt_"'
