options:
  formatter: stylish

rules:
  class-name-format:
    - 1
    -
      convention: 'mt_([a-z0-9\-]+)'
      convention-explanation: 'All class names must be prefaced with "mt_" and contain only lowercase letters and dashes afterward'
  function-name-format:
    - 1
    -
      convention: 'mt_([a-z0-9\-]+)'
      convention-explanation: 'All function names must be prefaced with "mt_" and contain only lowercase letters and dashes afterward'
  no-mergeable-selectors:
    - 2
    -
      whitelist:
        - '.mt_col-,#{$mt_bp}-$mt_i'
  placeholder-name-format:
    - 2
    -
      convention: 'mt_([a-z0-9\-]+)'
      convention-explanation: 'All placeholder names must be prefaced with "mt_" and contain only lowercase letters and dashes afterward'
  property-sort-order: 2
  variable-name-format:
    - 1
    -
      convention: 'mt_([a-z0-9\-]+)'
      convention-explanation: 'All variable names must be prefaced with "mt_" and contain only lowercase letters and dashes afterward'
