exclude: 'app/src/sass/_shame.scss'

linters:
    Comment:
        enabled: false
    Indentation:
        width: 4
    SpaceBetweenParens:
        spaces: 0
    StringQuotes:
        style: double_quotes
